#! /bin/bash 
room_name=$1
visitors_amount=$2

if [[ -d "$room_name" ]]; then
	if [[ "$visitors_amount" == "0" ]]; then
#		echo "" # dont print nothing when the amount equal zero
		printf ""
	elif [[ "$visitors_amount" -eq " " ]]; then 
		# if the visitors_amount input is empty
#		dos2unix -q $room_name/visitors.txt
		sort -rk2 $room_name/visitors.txt | sort -rsk3 | uniq -f2 | sort -rnk2 | cut -d" " -f3 | tail -n+1
	else
		# if the visitors_amount input is included
#		dos2unix -q $room_name/visitors.txt
		sort -rk2 $room_name/visitors.txt | sort -rsk3 | uniq -f2 | sort -rnk2 | cut -d" " -f3 | head -n$visitors_amount
	fi
else
	echo "room name doesn't exist."
fi
